[ADD] 견적내기 뷰 추가
DeveloperAcademy-POSTECH/MacC-Team-FourFour pull request #8
Opened 2022-10-10 05:40 UTC by KimDaeSeong8721

## ⁴/₄ 관련 이슈

- close #1 
## ⁴/₄ 작업내용

- 견적내기 뷰 UI를 구현하였습니다
- 컬렉션뷰의 선택기능을 구현하였습니다.
-  Rx적으로 코드를 리팩토링했습니다.

## ⁴/₄ PR 포인트

https://user-images.githubusercontent.com/69894461/194803595-8e014e6a-d991-4cc1-a681-fdd7bb902f63.mp4

**PR 포인트를 말하기에 앞서 사죄의 말씀을 드립니다.** PR을 올릴때 최대한 코드량을 줄여서 올리라고 했는데 제가 지키지 못했네요.
코드가 이렇게 길어질지 몰랐습니다 ㅜㅜ. 대부분의 코드가 UI컴포넌트 관련 코드라 너그러이,, 봐주시고 봐주시면 감사합니다. 다음부터는 이슈를 최대한 잘게 쪼개보도록 하겠습니다.

그래도 간단하게 코드의 구조를 설명하면
1 .UICollectionView + Extension 추가하였습니다.
2. 임시 MockData 추가하였습니다
3. ViewModelBinableType, ViewModelType 프로토콜 추가하였습니다
4. 이미지 Assets 추가하였습니다
5. MainStoryBoard 임시 뷰컨트롤러 추가하였습니다 ( 스토리보드랑 연결되어있어서 viewModel 주입하기가 어려워 이런 방식 진행)
6. 임시 Sample Model 추가하였습니다
7. 파일은 EstimationViewController, EstimatedViewModel 추가하였습니다
8.  EstimateViewController는 크게 View가 이미지사진뷰, 샘플 정보뷰, 바텀뷰,샘플컬렉션뷰 네가지 서브뷰로 이루어져 있습니다.
9. bind부분은 컬렉션뷰에서 사용자의 이벤트가 발생하면 input을 통해 받고 transform함수를 통해 output을 얻어내고 output을 통해 데이터바인딩을 진행합니다.
컬렉션뷰의 단일 선택기능을 제공하기 위해  ```collectionView.allowsMultipleSelection = false```와 ```override var isSelected를 이용하였습니다.
<img width="250" alt="image" src="https://user-images.githubusercontent.com/69894461/194804104-87074aac-d04a-4482-98d2-4a4e7b66e10d.png">

## ⁴/₄ 다음으로 진행될 작업
 - [ ] 장바구니 뷰 구현

2022-10-10 09:04 UTC, cozytk requested changes
![구현피그마](https://user-images.githubusercontent.com/59143479/194831310-6699b976-0386-4713-9d51-1ba203e35420.png)

코드량이 많긴 한데 이미 구조에 대해서 핸즈온 강의를 해주셔서 어떤 파일이 어떤 역할을 하는지 설명을 들어봤기 때문에 코드를 보는데 큰 어려움이 없었습니다!
UI를 디자인 요소에 거의 맞게 구현해 주신 것 같아요!!
일부 디자인과 다른 부분들이 있지만 ("장당"이라는 글자가 bold 처리되어있음, 샘플가격 5,000원이 위랑 라인이 안맞음) 그런 부분들은 디자인팀과 얘기를 해보면 될 것 같습니다!!!

더 천천히 꼼꼼히 보고 싶었는데 이렇게 보다가는 코드리뷰하다 MVP 개발 못할 거 같아서 리뷰 마치겠습니다!!!

2022-10-10 11:51 UTC, JIW00NG requested changes
보는데 이해하기 어려운 코드 없이 잘 작성해주신것 같네요!
고생하셨습니다!
enum Size를 통해 뷰를 설정하는 방향으로 진행할지 팀원들과 얘기해보면 좋을 것 같아요!

2022-10-10 11:51 UTC, JIW00NG commented on Samplero/Samplero/Global/Literal/ImageLiteral.swift
> +    static var shoppingBag: UIImage { .load(named: "ShoppingBag")}
이런식으로 사용하는거군요!
좋은건 따라하겠습니다 👍

2022-10-10 11:51 UTC, JIW00NG commented on Samplero/Samplero.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> -}
이건 왜 삭제된건가요?

2022-10-10 11:51 UTC, JIW00NG commented on Samplero/Samplero/Screen/Estimate/EstimateViewController.swift
> +    static let deviceHeight = UIScreen.main.bounds.size.height - ((UIApplication.shared.windows.first?.safeAreaInsets.top) ??  0.0) - 44.0
저도 궁금합니다.

2022-10-10 11:51 UTC, JIW00NG commented on Samplero/Samplero/Screen/Estimate/EstimateViewController.swift
> +    static let sampleCollectionBottomOffset = 14.0
추후 이렇게 상수값으로 넣을지 동적으로 넣을지 얘기가 필요할 듯 합니다.

2022-10-10 11:51 UTC, JIW00NG commented on Samplero/Samplero/Screen/Estimate/EstimateViewController.swift
> +    // View consists of roomImageView, sampleDetailView, bottomView
이렇게 하는거 좋네요!

2022-10-10 11:51 UTC, JIW00NG commented on Samplero/Samplero/Screen/Estimate/EstimateViewController.swift
> +        imageView.image = ImageLiteral.sampleRoom
👍

2022-10-10 11:51 UTC, JIW00NG commented on Samplero/Samplero/Screen/Estimate/View/SampleDetailView.swift
> +    private let h1StackView: UIStackView = {
p3.
h1이 무엇을 의미하는 것인가요?
코드만 보고 이해할 수 있었으면 좋겠습니다.

2022-10-10 11:51 UTC, JIW00NG commented on Samplero/Samplero/Screen/Estimate/View/SampleDetailView.swift
> +    private let vStackView: UIStackView = {
p2.
vertical StackView인 것은 알겠으나
```swift
private let sampleDetailStackView
```
처럼 해당 StackView가 무엇인지 확실하게 해주셨으면 합니다.

2022-10-11 00:09 UTC, Minkyeong-Ko approved these changes
다른 분들이 정말 열심히 봐 주셨네요! 수고하셨습니다 밀러👍  코드 보고 많이 배웠습니다  :)

2022-10-11 00:09 UTC, Minkyeong-Ko commented on Samplero/Samplero/Global/Protocol/ViewModelBindableType.swift
> +//  MVVMKaKaoProfile
P3.
이 부분 Samplero로 수정해 주시면 좋을 것 같아요!

2022-10-11 00:09 UTC, Minkyeong-Ko commented on Samplero/Samplero/Screen/Estimate/EstimateViewController.swift
> +        label.textAlignment =  .left
오 배우고 갑니다 코지!

2022-10-11 00:13 UTC, Minkyeong-Ko commented on Samplero/Samplero/Global/Protocol/ViewModelType.swift
> +//  KakaoProfile
p2.
마찬가지로 KaKaoProfile로 되어 있습니다!

2022-10-11 02:27 UTC, KimDaeSeong8721 commented on Samplero/Samplero/Global/Protocol/ViewModelBindableType.swift
> +//  MVVMKaKaoProfile
```suggestion
//  Samplero
```

2022-10-11 02:32 UTC, KimDaeSeong8721 commented on Samplero/Samplero/Model/Sample.swift
> +    let maker: String
수정하겠습니다

2022-10-11 02:39 UTC, KimDaeSeong8721 commented on Samplero/Samplero/Screen/Estimate/EstimateViewController.swift
> +    static let deviceHeight = UIScreen.main.bounds.size.height - ((UIApplication.shared.windows.first?.safeAreaInsets.top) ??  0.0) - 44.0
공부해오겠습니다

2022-10-11 02:59 UTC, KimDaeSeong8721 commented on Samplero/Samplero/Screen/Estimate/View/CommonStackView.swift
> +class CommonStackView: UIStackView {
EstimateCommonStackView로 고치겠습니다!

2022-10-11 03:00 UTC, KimDaeSeong8721 commented on Samplero/Samplero/Screen/Estimate/View/SampleDetailView.swift
> +    private let h1StackView: UIStackView = {
firstHorizontalView로 고치겠습니다!

2022-10-11 03:01 UTC, KimDaeSeong8721 commented on Samplero/Samplero/Screen/Estimate/View/SampleDetailView.swift
> +    private let vStackView: UIStackView = {
verticalStackView로 고치겠습니다!

2022-10-11 03:06 UTC, KimDaeSeong8721 commented on Samplero/Samplero/Screen/Estimate/View/cell/SampleCollectionViewCell.swift
> +                UIColor.systemBlue.cgColor : UIColor.clear.cgColor
다시 가독성 좋게 수정해보겠습니다!

2022-10-11 08:17 UTC, cozytk commented on Samplero/Samplero/Screen/Estimate/View/SampleDetailView.swift
> +         sizeStackView.setValueLabel(with: sample.size.toString)
```suggestion
        thicknessStackView.setValueLabel(with: "\(sample.thickness.description)cm")
        sizeStackView.setValueLabel(with: sample.size.toString)
```

2022-10-11 08:17 UTC, cozytk commented on Samplero/Samplero/Screen/Estimate/EstimateViewController.swift
> +        label.textAlignment =  .natural
```suggestion
        label.textAlignment = .natural
```

2022-10-11 08:17 UTC, cozytk commented on Samplero/Samplero/Screen/Estimate/EstimateViewController.swift
> +        label.textAlignment =  .natural
```suggestion
        label.textAlignment = .natural
```

2022-10-11 08:18 UTC, cozytk approved these changes

2022-10-11 08:19 UTC, merged